title: Lyons Family Homeschool
description: >-
  A homeschool website for the Lyons family.

baseurl: "/homeschool" 
url: "https://maureensmusings.github.io"

# Theme
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Include video files
include:
  - jojo-vids

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/